services:

  wood_fastapi:
    build: .
    image: wood_fastapi
    container_name: wood_fastapi
    restart: always
    links:
      - "postgres_wood:dbps"
    networks:
      - dbnet
    volumes:
      - ./wood_app:/app/wood_app
    ports:
      - "8000:8000"
    depends_on:
      - postgres_wood


  postgres_wood:
    image: postgres:17-alpine
    container_name: psgr_wood
    volumes:
      - postgres-data_wood:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - dbnet


networks:
  dbnet:
    driver: bridge


volumes:
  postgres-data_wood: